### ISSUE TITLE
ValueError: Invalid input. Supports one of [dict,list,DictConfig,ListConfig,dataclass,dataclass instance,attr class,attr class instance] (omegaconf.resolve)

### ISSUE THREAD

**Issue by shulgart** [cvg/glue-factory#138]
An error in the title is preventing from running training script with any of the available configs via ````python3 -m gluefactory.train````

Traceback points to line 705 in ````gluefactory/train.py````:
````
File "C:\pyProjects\glue-factory\gluefactory\train.py", line 705, in <module>
    conf = OmegaConf.merge(OmegaConf.resolve(OmegaConf.load(args.conf)), conf)
````
Looked into it and found that ````OmegaConf.resolve(...)```` returns ````None```` value.

In case anybody finds themselves in the same situation reverting the latest commit helps. Particularly, a 
````
git checkout c8e825a9ef8b108d3583cb34885a4bc0563ee99e
```` 
works as a temporal workaround

**Comment by RaphaelKreft** [comment]
Encountered the same problem and solved the issue the same way. 
I don't know what `OmegaConf.resove()` contributes. But It works fine without, so one could consider removing it again.

**Comment by Phil26AT** [comment]
Hi @shulgart @RaphaelKreft, sorry for this issue. I pushed a fix to #142, can you confirm whether this solves your issue?

**Comment by shulgart** [comment]
@Phil26AT I'm sorry it took me too long to answer. I tried this fix on my toy custom dataset and now it's going through ````omegaconf.resolve()```` stage flawlessly.

Unfortunately, issue https://github.com/cvg/glue-factory/issues/139 still persists. More info I tried to post there.

Thank you for your cool work!

**Comment by Phil26AT** [comment]
Great, I close this issue and we keep #139 open for now.

Thank you for reporting this problem!
